<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="en" xml:lang="en" xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title><?php print $page_title; ?></title>
    
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
    
    <style>
      body, td { font-family: sans-serif; }
      body { margin: 0; padding: 0; background-color: #CCCCCC;}
      h2 { margin: 0 0 .5em 0; }
      a { color: #0000EE; }
      
      .container { padding: 1em; }
      #header { background-color: #9999CC; color: #000;  border-bottom: 2px solid #7777AA; margin-bottom: 1em;}
      #checks { margin-bottom: 4em; }
      #messenger .section { font-weight: bold; border: 2px solid #7777AA; }
      div.section { background-color: #FFFFFF; padding: 1em; margin-bottom: 1em; }
      
      #totals h2 { margin-bottom: 0; padding: .5em 1em; }
      
      table { border-collapse: collapse; text-align: left; width: 100%; }
      td, th { border: 1px solid #000; font-size: 75%; vertical-align: baseline; color: #000; }
      th { font-weight: bold; }
      thead th { background-color: #9999CC; }
      tbody th { background-color: #CCCCFF; }
      th.check  { width: 200px; }
      th.result { width: 150px; }
      
      ul.legend, #messenger ul { list-style: none; margin: 0; padding: 0; }
      ul.legend li { margin-bottom: .5em; padding: .2em .5em; width: 300px; }
      
      #logout, ul.controls { float: right; list-style: none; margin: 0; padding: 0; }
      #logout li, ul.controls li { float: left; }
      ul.controls { list-style: none; margin: 0 0 0 0; padding: 0; float: right; }
      ul.controls li { margin-left: 1em; }
      ul.controls a { display: block; border: 2px solid #7777AA; background-color: #CCCCCC; font-weight: bold; text-decoration: none; padding: .2em .5em; }
      ul.controls a:hover { background-color: #FFF; }
      
      h2.ok, li.ok, 
      tr.ok .result { background-color: #CCFF99; }
      h2.optional, li.optional, 
      tr.optional .result { background-color: #CCFFFF; } 
      h2.warning, li.warning, 
      tr.warning .result { background-color: #FFCC66; }
      h2.error, li.error, 
      tr.error .result { background-color: #FF9999; font-weight: bold; }
      
      .form-item, .form-buttons { margin: 0 0 1em 0; }
      .form-buttons { padding-left: 100px; }
      .form-item label { display: inline-block; width: 100px; }
    </style>
  </head>
  
  <body>
  
    <div id="header" class="container">
      <?php if($show_logout): ?>
        <ul id="logout">
          <li><a href="<?php print $url_logout; ?>">Logout</a></li>
        </ul>
      <?php endif; ?>
      
      <h1>PHP Hosting check</h1>  
      
      <?php if($controls): ?>
        <ul class="controls">
          <?php foreach($controls AS $url => $label): ?>
            <li><a href="<?php print $url; ?>"><?php print $label; ?></a></li>
          <?php endforeach; ?>
        </ul>
      <?php endif ?>
      
    </div>
    
  <?php if(count($messages)): ?>
    <div id="messenger" class="container"><div class="section">
      <ul>
        <?php foreach($messages AS $msg): ?>
          <li><?php print $msg; ?></li>
        <?php endforeach; ?>
      </ul>
    </div></div>
    
  <?php endif; ?>
  
  <?php print $content; ?>
  
  </body>
  
</html>