
<style>

    body, td {
        font-family: sans-serif;
    }
    body {
        margin: 0;
        padding: 0;
        background-color: #CCC;
    }

    h2 {
        margin: 0 0 .5em 0;
    }

    a {
        color: #00E;
    }

    .container {
        padding: 1em;
    }

    #header {
        background-color: #99C;
        color: #000;
        border-bottom: 2px solid #77A;
        margin-bottom: 1em;
    }

    #totals h2 {
        margin-bottom: 0;
        padding: .5em 1em;
    }

    #results {
        margin-bottom: 4em;
    }

    div.section {
        background-color: #FFF;
        padding: 1em;
        margin-bottom: 1em;
    }

    table {
        border-collapse: collapse;
        text-align: left;
        width: 100%;
    }
    td, th {
        border: 1px solid #999;
        font-size: 75%;
        vertical-align: baseline;
        color: #000;
        padding: .3em;
    }
    th {
        font-weight: bold;
    }
    thead th {
        background-color: #99C;
    }
    tbody th {
        background-color: #CCF;
    }
    th.info {
        width: 200px;
    }
    th.value {
        width: 150px;
    }
    td.messages ul {
        margin: 0;
        padding: 0 0 0 2em;
    }
    td.messages li {
        margin-bottom: .5em;
    }
    td.messages li:last-child {
        margin-bottom: 0;
    }

    ul.legend {
        list-style: none;
        margin: 0;
        padding: 0;
    }
    ul.legend li {
        margin-bottom: .5em;
        padding: .2em .5em;
    }

    #logout {
        float: right;
        list-style: none;
        margin: 0;
        padding: 0;
    }
    #logout li {
        display: inline-block;
    }
    #logout a {
        text-decoration: none;
        font-size: 90%;
    }

    h2.success, li.success,
    tr.success .value {
        background-color: #CF9;
    }
    h2.optional, li.optional,
    tr.optional .value {
        background-color: #CFF;
    }
    h2.warning, li.warning,
    tr.warning .value {
        background-color: #FC6;
    }
    h2.failure, li.failure,
    tr.failure .value {
        background-color: #F99;
    }

    .form-item, .form-buttons {
        margin: 0 0 1em 0;
    }
    .form-buttons {
        padding-left: 100px;
    }
    .form-item label {
        display: inline-block;
        width: 100px;
    }

    .button-list, .button-list li {
        margin: 0;
        padding: 0;
        list-style: none;
    }
    .button-list li {
        margin: 0 .5em 1em 0;
    }
    .button-list li {
        display: inline-block;
    }
    .button {
        line-height: 1.6em;
        text-decoration: none;
        display: inline-block;
        padding: 0 .5em;
        background: transparent;
        border: 1px solid #009;
        -webkit-border-radius: 5px;
        -moz-border-radius: 5px;
        border-radius: 5px;
    }
    .button:hover {
        background-color: #009;
        color: #FFF;
    }

</style>
